ci: enable more linters
chocolacula/gdmd pull request #22
Opened 2024-12-02 21:31 UTC by ccoVeille

the default ones are not enough

fixes #15

2024-12-03 20:18 UTC, chocolacula requested changes

2024-12-03 20:18 UTC, chocolacula commented on .golangci.yml
> +      - name: var-naming
let's add atomic and wait-group checks

2024-12-03 20:19 UTC, chocolacula commented on .golangci.yml
> +    locale: US
I don't mind but I'm ok with UK spelling too.

2024-12-05 00:13 UTC, ccoVeille commented on .golangci.yml
> +      - name: blank-imports
a blank import is

```go

import(
_ "encoding/json"
)
```

The code is imported but not used

2024-12-05 00:18 UTC, ccoVeille commented on .golangci.yml
> +      - name: blank-imports
https://github.com/mgechev/revive/blob/master/rule/blank_imports.go

2024-12-06 19:06 UTC, chocolacula approved these changes

2024-12-06 19:06 UTC, chocolacula commented on .golangci.yml
> +      - name: blank-imports
Thanks for the explanation

2024-12-06 19:10 UTC, merged